version: '3.8'

services:
  frontend:
    build:
      context: ./requirement-analyzer-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 